language: rust
rust:
  - stable
  - beta
  - nightly
cache:
  cargo: true
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build -p ipfs-api --verbose --features actix --no-default-features
  - cargo test -p ipfs-api --verbose --features actix --no-default-features
