[package]
name                      = "ipfs-cli"
version                   = "0.4.0"
license                   = "MIT OR Apache-2.0"
authors                   = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
clap                      = "2.27"
futures                   = "0.1"
ipfs-api                  = { path = "../ipfs-api" }
tokio-core                = "0.1"
