[package]
name          = "ipfs-api"
version       = "0.4.0"
authors       = ["Ferris Tseng <ferristseng@fastmail.fm>"]

[dependencies]
futures       = "0.1"
hyper         = "0.11"
serde         = "1.0"
serde_derive  = "1.0"
serde_json    = "1.0"
tokio-core    = "0.1"
